import { ObstacleConfig } from './Constants';

export const OBSTACLE_CONFIGS: Record<string, ObstacleConfig> = {
  cop: {
    type: 'cop',
    spawnWeight: 50,
    color: 0x0000ff,
    width: 50,
    height: 70,
    collisionWidthRatio: 0.6,
    collisionHeightRatio: 1.0,
    canJump: false,
    canSlide: false,
    canLaneChange: true,
    speed: 0,
    zigzag: false,
  },
  maga: {
    type: 'maga',
    spawnWeight: 35,
    color: 0xff0000,
    width: 50,
    height: 55,
    collisionWidthRatio: 0.7,
    collisionHeightRatio: 0.8,
    canJump: true,
    canSlide: false,
    canLaneChange: true,
    speed: 100,
    zigzag: false,
  },
  hater: {
    type: 'hater',
    spawnWeight: 15,
    color: 0x800080,
    width: 45,
    height: 60,
    collisionWidthRatio: 0.5,
    collisionHeightRatio: 1.0,
    canJump: true,
    canSlide: true,
    canLaneChange: true,
    speed: 0,
    zigzag: true,
  },
};
